// Adapted from safe.wei: one HTML file, no runtime network/resource loaders.
import { build, transform } from 'esbuild';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
const root = new URL('..', import.meta.url).pathname;
const read = f => readFileSync(root + f, 'utf8');
const digest = createHash('sha256');
for (const f of readdirSync(root + 'src').sort()) digest.update(f).update(read('src/' + f));
const id = digest.digest('hex').slice(0, 10);
const js = (await build({ entryPoints: [root + 'src/app.js'], bundle: true, minify: true, format: 'iife', target: 'es2020', write: false, legalComments: 'none', charset: 'utf8', define: { __BUILD__: JSON.stringify(id) } })).outputFiles[0].text.trim();
const css = (await transform(read('src/style.css'), { loader: 'css', minify: true })).code.trim();
if (/<\/script/i.test(js)) throw Error('Unsafe inline script terminator');
// Config that may need replacing after deployment (the WalletConnect project ID, links to safe.wei and the source) lives outside src/ and goes
// into its own tiny first chunk, cut at <!--config--> (scripts/deploy-lib.mjs): replacing it redeploys only
// that chunk and the app contract.
const config = JSON.parse(read('config/walletconnect.json'));
if (!/^[0-9a-f]{32}$/.test(config.projectId)) throw Error('config/walletconnect.json: projectId must be 32 hex characters');
// Links to other places (safe.wei's gateways, where Safe transactions are handed off, and the source code), in the
// same first chunk: config/links.json.
const links = JSON.parse(read('config/links.json'));
const url = (u) => typeof u === 'string' && /^https:\/\/[a-z0-9-]+(\.[a-z0-9-]+)+\/[\w./-]*$/.test(u);
if (!Array.isArray(links.safe) || !links.safe.length || !links.safe.every((u) => url(u) && u.endsWith('/')) || !url(links.source + '/'))
  throw Error('config/links.json: safe must be https:// gateway URLs ending in /, source an https:// URL');
const OPEN = '<!doctype html><html lang="en"><head><meta charset="utf-8">';
const shell = read('src/index.html').replace(/>\s+</g, '><');
if (!shell.startsWith(OPEN)) throw Error('src/index.html must start with ' + OPEN);
const html = OPEN + '<script>var WC_PROJECT="' + config.projectId + '",LINKS=' + JSON.stringify({ safe: links.safe, source: links.source }) + '</script><!--config-->' + shell.slice(OPEN.length).replace('<!--CSS-->', () => '<style>' + css + '</style>').replace('<!--JS-->', () => '<script>' + js + '</script>');
for (const re of [/<script[^>]+src\s*=/i, /<link[^>]+rel=["']?stylesheet/i, /@import/i, /\b(?:XMLHttpRequest|EventSource|importScripts)\s*\(/, /\bimport\s*\(/, /(?:src|poster)\s*=\s*["']?(?:https?:)?\/\//i]) {
  if (re.test(html)) throw Error('Remote resource/network loader check failed: ' + re);
}
// Network: only src/net.js opens connections (WalletConnect's relay, and JSON-RPC reads a wallet cannot
// serve), so no other source file may, and the bundle holds exactly one fetch( and one WebSocket(.
for (const f of readdirSync(root + 'src').filter((f) => f.endsWith('.js') && f !== 'net.js'))
  if (/\b(?:fetch|WebSocket)\s*\(/.test(read('src/' + f))) throw Error('src/' + f + ': network requests go through src/net.js only');
for (const re of [/\bfetch\s*\(/g, /\bWebSocket\s*\(/g]) if ((js.match(re) || []).length > 1) throw Error('More than one ' + re + ' in the bundle: network requests go through src/net.js only');
// Scan CSS separately: the case-insensitive HTML regex would mistake JavaScript's
// `new URL(...)` constructor for a CSS url(...) resource reference.
if (/url\(\s*["']?(?!data:|#)[^)]/i.test(css)) throw Error('Remote CSS resource check failed');
const raw = Buffer.byteLength(html), gzip = gzipSync(html).length;
if (raw > 300000) throw Error('Production HTML exceeds 300,000 bytes');
mkdirSync(root + 'dist', { recursive: true });
writeFileSync(root + 'dist/index.html', html);
writeFileSync(root + 'docs/size.md', '# Size report\n\nGenerated by `npm run build`.\n\n| Build | Raw HTML | gzip | JavaScript | CSS |\n| --- | ---: | ---: | ---: | ---: |\n| `' + id + '` | ' + raw + ' B | ' + gzip + ' B | ' + Buffer.byteLength(js) + ' B | ' + Buffer.byteLength(css) + ' B |\n\nTarget below 100,000 bytes; hard limit 300,000 bytes. No remote code/assets. Network requests only through src/net.js (the WalletConnect relay and RPC, or your history RPC); chain reads otherwise use the wallet provider.\n');
console.log('Build ' + id + ': ' + raw + ' B raw, ' + gzip + ' B gzip');
