// Adapted from safe.wei: one HTML file, no runtime network/resource loaders.
import { build, transform } from 'esbuild';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
const root = new URL('..', import.meta.url).pathname;
const read = f => readFileSync(root + f, 'utf8');
const digest = createHash('sha256');
for (const f of readdirSync(root + 'src').sort()) digest.update(f).update(read('src/' + f));
const id = digest.digest('hex').slice(0, 10);
const js = (await build({ entryPoints: [root + 'src/app.js'], bundle: true, minify: true, format: 'iife', target: 'es2020', write: false, legalComments: 'none', charset: 'utf8', define: { __BUILD__: JSON.stringify(id) } })).outputFiles[0].text.trim();
const css = (await transform(read('src/style.css'), { loader: 'css', minify: true })).code.trim();
if (/<\/script/i.test(js)) throw Error('Unsafe inline script terminator');
const html = read('src/index.html').replace(/>\s+</g, '><').replace('<!--CSS-->', () => '<style>' + css + '</style>').replace('<!--JS-->', () => '<script>' + js + '</script>');
for (const re of [/<script[^>]+src\s*=/i, /<link[^>]+rel=["']?stylesheet/i, /@import/i, /\b(?:fetch|XMLHttpRequest|WebSocket|EventSource|importScripts)\s*\(/, /\bimport\s*\(/, /(?:src|poster)\s*=\s*["']?(?:https?:)?\/\//i]) {
  if (re.test(html)) throw Error('Remote resource/network loader check failed: ' + re);
}
// Scan CSS separately: the case-insensitive HTML regex would mistake JavaScript's
// `new URL(...)` constructor for a CSS url(...) resource reference.
if (/url\(\s*["']?(?!data:|#)[^)]/i.test(css)) throw Error('Remote CSS resource check failed');
const raw = Buffer.byteLength(html), gzip = gzipSync(html).length;
if (raw > 200000) throw Error('Production HTML exceeds 200,000 bytes');
mkdirSync(root + 'dist', { recursive: true });
writeFileSync(root + 'dist/index.html', html);
writeFileSync(root + 'docs/size.md', '# Size report\n\nGenerated by `npm run build`.\n\n| Build | Raw HTML | gzip | JavaScript | CSS |\n| --- | ---: | ---: | ---: | ---: |\n| `' + id + '` | ' + raw + ' B | ' + gzip + ' B | ' + Buffer.byteLength(js) + ' B | ' + Buffer.byteLength(css) + ' B |\n\nTarget below 100,000 bytes; hard limit 200,000 bytes. No remote code/assets or runtime network loaders. Chain reads use the wallet provider.\n');
console.log('Build ' + id + ': ' + raw + ' B raw, ' + gzip + ' B gzip');
